### PR TITLE
Minor changes in load_ifgram.py

### PR DESCRIPTION
**Pull request by bjmarfito**
- Proposed minor changes in load_ifgram.py due to changes made by MintPy PRs https://github.com/insarlab/MintPy/pull/791 and https://github.com/insarlab/MintPy/pull/780.

### CODE REVIEW

**Comment by yunjunz** [comment]
I plan to issue another PR tomorrow to introduce some big changes to `load_data.py`, including removing the `only_load_ionosphere` key. You may want to wait a bit before merging this PR.

**Comment by yunjunz** [comment]
The PR (https://github.com/insarlab/MintPy/pull/796) has been merged.

**Comment by bjmarfito** [comment]
Thank you @yunjunz!

**Comment by bjmarfito** [comment]
Updated this code due to changes made by @yunjunz in MintPy.

**Review by mirzaees — APPROVED** [review]
Looks good to me, thank you @bjmarfito

**Pull request merged**
